### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mosharky** [Reavershark/centered-inventory#1]
[Here's the latest.log](https://pastebin.com/JzrT3eiH)

**Comment by jnms-me** [comment]
You have a lot of other mods loaded:
- waterdripsound
- particlerain
- fallingleaves
- mm
- replanter
- horsestatsvanilla
- modmenu
- jankson
- cloth-basic-math
- betterdroppeditems
- libninepatch
- voidfog
- libgui
- cloth-config2
- entityculling
- seamless_loading_screen
- bettermounthud
- centeredinventory
- malilib
- extrasounds
- kirin
- itemscroller
- advancedcompass
- presencefootsteps

Looking around i found a bug that might be conflicting with another badly-configured mod.
I'll update the mod soon.
From the crash log i can't tell which mod is causing the conflict.

**Comment by jnms-me** [comment]
This should be fixed in the latest version.
If it isn't, it probably isn't this mod that's causing your crash.
