### ISSUE TITLE
Recipe book closes after selecting recipe

### ISSUE THREAD

**Issue by postout** [Reavershark/centered-inventory#2]
MC Version: 1.17
Fabric Version: 0.7.4 / API 0.35.2
Mod Version: 1.0.0

Expected result: recipe book doesn't close after clicking a recipe. 

Actual result: recipe book closes after clicking a recipe.

**Comment by jnms-me** [comment]
Thanks for the report!
This was working previously but only in my dev client.
Will be fixed in v1.0.2
