### ISSUE TITLE
overrides resourcepack GUI textures

### ISSUE THREAD

**Issue by danieljross** [Reavershark/centered-inventory#3]
It appears the mod will replace custom inventory gui texture(s) supplied by a resource pack with Minecraft's default one. 
For example, a resourcepack that's meant to turn all UI into "dark mode" has an inventory UI that looks like default Minecraft.

**Comment by jnms-me** [comment]
Can you link which resource pack in particular you're referring to?

**Comment by danieljross** [comment]
It was vanilla tweaks dark GUI pack. When I removed the mod I must have coincidentally shuffled some resource packs around at the same time and got the UI to look as expected, falsely concluding it was the mod's doing. With my newly re-shuffled resource packs and re-installation of the mod, I'm not seeing the issue anymore. Must have been another resource pack creating the problem. My mistake, apologies.
